#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# setup all the paths
export GROOVY_HOME=/usr/local/opt/groovy/libexec
export JAVA_1_7_HOME="$(/usr/libexec/java_home -v 1.7)"
export JAVA_1_8_HOME="$(/usr/libexec/java_home -v 1.8)"
export PALANTIR_JAVA_HOME=$JAVA_1_8_HOME
export JAVA_HOME=$JAVA_1_8_HOME
export NODE_PATH=/usr/local/lib/node:/Users/wmanning/.node/lib/node_modules
export PATH=$HOME/.node/bin:/usr/local/share/npm/bin:/usr/local/bin:$PATH
export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"
export WORKON_HOME=$HOME/.virtualenvs
export GRADLE_USER_HOME=/Volumes/git/.gradle

# less is more
export GIT_PAGER='less -r'
export GIT_NOTES_REF=refs/notes/web-backports
export EDITOR=emacs

# define aliases here
alias ll='ls -ltr'
alias tarz='tar -czvf'
alias untarz='tar -xzvf'
alias glog='git log --pretty=oneline -n 10'
alias gw='./gradlew'

# homebrew autocompletion
source /usr/local/bin/virtualenvwrapper.sh
source /Users/wmanning/.iterm2_shell_integration.`basename $SHELL`
source /usr/local/dev-env/bin/profile
